[package]
name = "sct-reader"
version = "0.1.0"
edition = "2021"
authors = ["Caspian Merlin <chpmerlin@gmail.com>"]
description = "A Rust crate for deserialising sector (.sct) files used by online ATC clients such as EuroScope and VRC."
repository = "https://github.com/azimuth-radar/sct-reader"
homepage = "https://github.com/azimuth-radar/sct-reader"
license = "BSD-3-Clause"
keywords = ["flightsim", "vatsim", "flight_simulation", "sector_file"]
categories = ["parsing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
